services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    restart: always
    container_name: wordpress
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WP_SITE_URL: http://localhost:8080
      WP_ADMIN_USER: admin
      WP_ADMIN_PASSWORD: password
      WP_ADMIN_EMAIL: admin@example.com
      WP_POST_URL_STRUCTURE: /blog-post/%postname%
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins
      - ./themes:/var/www/html/wp-content/themes
      - ./uploads:/var/www/html/wp-content/uploads
      - ./wp-config.php:/var/www/html/wp-config.php
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./scripts:/var/www/html/scripts
      - ./src:/var/www/html/src
      - ./tests:/var/www/html/tests
      - ./phpunit.xml:/var/www/html/phpunit.xml
      - ./build:/var/www/html/build

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  wordpress:
  db:
