name: Deploy to Dev

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get EC2 Public IP
        id: get_ec2_ip
        run: |
          EC2_DEV_TAG=${{ vars.SERVICE_NAME }}-dev-web
          PUBLIC_IP_DEV=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=${EC2_DEV_TAG}" --query "Reservations[*].Instances[*].PublicIpAddress" --output text)
          echo "PUBLIC_IP=$PUBLIC_IP_DEV" >> $GITHUB_ENV
      - name: Print public IP
        run: |
          echo ${{ env.PUBLIC_IP }}

    #   - name: Deploy to EC2
    #     uses: appleboy/ssh-action@v0.1.3
    #     with:
    #       host: ${{ secrets.EC2_HOST }}
    #       username: ec2-user
    #       key: ${{ secrets.EC2_SSH_KEY }}
    #       script: |
    #         docker pull ghcr.io/${{ github.repository }}:latest
    #         docker stop demo || true
    #         docker rm demo || true
    #         docker run -d --name my-app -p 80:80 ghcr.io/${{ github.repository }}:latest
