name: Build and Push Docker Image

on:
  workflow_call:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Print github object
        run: |
          echo "${{ toJSON(github) }}"

      # - name: Create version.json
      #   run: |
      #     LATEST_TAG=$(git describe --tags --abbrev=0)
      #     VERSION=$(date +%Y.%m.%d).${{ github.run_number }}
      #     echo '{ "version": "'${VERSION}'", "commit": "'${{ github.sha }}'", "tag": "'${LATEST_TAG}'" }' > version.json

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: |
      #       ghcr.io/${{ github.repository }}:latest
